# Generated by Django 4.1.7 on 2023-11-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gaza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
