# Generated by Django 4.2.6 on 2023-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gaza', '0002_alter_map_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
