# Generated by Django 4.1.7 on 2023-11-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gaza', '0004_map_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
